name: Deploy to Fly.io
on:
  workflow_run:
    workflows: ['Rust']
    types: [completed]
    branches: [ main ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}

jobs:
  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: flyctl deploy
